default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sales_tax_challenge_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: sales_tax_challenge_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: sales_tax_challenge_production
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
